export const TokenType = Object.freeze({
    HEADING_1_MARKER: "HEADING_1_MARKER",
    HEADING_2_MARKER: "HEADING_2_MARKER",
    HEADING_3_MARKER: "HEADING_3_MARKER",
    HEADING_4_MARKER: "HEADING_4_MARKER",
    HEADING_5_MARKER: "HEADING_5_MARKER",
    HEADING_6_MARKER: "HEADING_6_MARKER",
    BOLD_START: "BOLD_START",
    BOLD_END: "BOLD_END",
    ITALIC_START: "ITALIC_START",
    ITALIC_END: "ITALIC_END",
    BLOCKQUOTE_MARKER: "BLOCKQUOTE_MARKER",
    INLINE_CODE_START: "INLINE_CODE_START",
    INLINE_CODE_END: "INLINE_CODE_END",
    LINK_TEXT_START: "LINK_TEXT_START",
    LINK_TEXT_END: "LINK_TEXT_END",
    LINK_URL_START: "LINK_URL_START",
    LINK_URL_END: "LINK_URL_END",
    IMAGE_MARKER: "IMAGE_MARKER",
    IMAGE_ALT_TEXT_MARKER: "IMAGE_ALT_TEXT_MARKER",
    IMAGE_URL_MARKER: "IMAGE_URL_MARKER",
    BLOCK_CODE_START: "BLOCK_CODE_START",
    BLOCK_CODE_END: "BLOCK_CODE_END",
    TEXT: "TEXT"
})

export class Token {
    constructor(type, lexeme) {
        this.type = type;
        this.lexeme = lexeme;
    }
}